version: "3.1"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - 3306:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
